#!/usr/bin/env python3

from src.DataModels import (
    MinimalAnswer,
    StudentSearchResultsAndAnswer,
    UnansweredQuestion,
    AnsweredQuestion,
    RagDataset
)


class Evaluator:
    '''
    Class for evaluate the datas
    '''

    def __init__(self) -> None:
        '''
        Initialize the evaluater

        Args:
            None
        Return:
            None
        '''
        pass

    def print_evaluation_results(
                self,
                student_answer: StudentSearchResultsAndAnswer,
                dataset_answer: RagDataset,
                overlaps: list[int],
                k: int,
                max_context_length: int
            ) -> None:
        '''
        Print the evaluation results

        Args:
            student_answer: StudentSearchResultsAndAnswer =
                The answer generated by the student
            dataset_answer: RagDataset = The references datas
            overlaps: list[int] = The different overlap to check
            k: int = The maximum number of source to check for each question
            max_context_length: int = The maximum number
                of characters inside a chunk
        Return:
            None
        '''
        # Handle invalid overlaps
        if any(ov > 100 or ov < 0 for ov in overlaps):
            raise Exception("Invalid overlap value")

        # Check the context_lengths
        is_valid_data: bool = True
        for answer in student_answer.search_results:
            for source in answer.retrieved_sources:
                context_length: int = int(
                    source.last_character_index -
                    source.first_character_index + 1
                )
                if context_length > max_context_length:
                    is_valid_data = False

        print(f"Student data is valid: {is_valid_data}")

        if not is_valid_data:
            return

        # Calculate the questions stats
        total_questions: int = len(dataset_answer.rag_questions)
        dataset_answered_questions: list[
            AnsweredQuestion | UnansweredQuestion
        ] = (
            dataset_answer.rag_questions
        )
        sourced_questions: int = len([
            q for q in dataset_answered_questions
            if isinstance(q, AnsweredQuestion) and len(q.sources) > 0
        ])
        sourced_student_questions: int = len([
            q for q in student_answer.search_results
            if len(q.retrieved_sources) > 0
        ])

        # Print the questions stats
        print(f"Total number of questions: {total_questions}")
        print(f"Total number of questions with sources: {sourced_questions}")
        print(
            "Total number of questions with "
            f"student sources: {sourced_student_questions}\n"
        )

        # Print Recall
        print(
            "Evaluation Results\n"
            "========================================"
        )

        # Calculate the evaluated questions
        evaluated_questions: list[tuple[
            MinimalAnswer, AnsweredQuestion | UnansweredQuestion
        ]] = []

        for student_q in student_answer.search_results:
            for dataset_q in dataset_answer.rag_questions:
                same_q: bool = student_q.question_id == dataset_q.question_id

                # Handle mypy error
                if isinstance(dataset_q, AnsweredQuestion):
                    dataset_has_source: bool = len(dataset_q.sources) > 0

                    if same_q and dataset_has_source:
                        evaluated_questions.append(
                            (student_q, dataset_q)
                        )

        print(f"Questions evaluated: {len(evaluated_questions)}")

        # Calculate and print the Recall@k scores
        for overlap in overlaps:
            if len(evaluated_questions) != 0:
                score: float = self._get_score(
                    evaluated_questions,
                    overlap,
                    k
                ) / len(evaluated_questions) * 100
                print(f"Recall@{overlap}: {score:.3f}")

            else:
                print(f"Recall@{overlap}: {0.0:.3f}")

    def _get_score(
                self,
                evaluated_questions: list[tuple[
                    MinimalAnswer, AnsweredQuestion | UnansweredQuestion
                ]],
                overlap: int,
                k: int
            ) -> float:
        '''
        Return the Recall@k score

        Args:
            evaluated_questions: list[tuple[
                MinimalAnswer, AnsweredQuestion
            ]] = The question to calculte the Recall@k score
            overlap: int = The current overlap for the Recall@k
            k: int = The maximum number of source to check for each question
        Return
            res: int = The Recall@k score
        '''
        res: float = 0.0

        # For each duo of questions
        for (student_q, dataset_q) in evaluated_questions:

            correcte_questions: int = 0

            # We compare the dataset source
            if not isinstance(dataset_q, AnsweredQuestion):
                continue
            for dataset_source in dataset_q.sources:

                length: int = min([
                    len(student_q.retrieved_sources),
                    k
                ])

                # With each student source
                for i in range(length):

                    student_source = student_q.retrieved_sources[i]

                    # Same file
                    student_file: str = student_source.file_path
                    dataset_file: str = dataset_source.file_path
                    same_file: bool = student_file == dataset_file

                    # Correcte overlap
                    correcte_source: bool = self._is_correcte_source(
                            overlap,
                            (
                                student_source.first_character_index,
                                student_source.last_character_index
                            ),
                            (
                                dataset_source.first_character_index,
                                dataset_source.last_character_index
                            )
                    )

                    # If the student source is good
                    if same_file and correcte_source:

                        # We update the number of good student sources
                        correcte_questions += 1

                        # And redo it with the next dataset_source
                        break

            res += correcte_questions / len(dataset_q.sources)

        return res

    def _is_correcte_source(
                self,
                overlap: int,
                student_chunk: tuple[int, int],
                dataset_chunk: tuple[int, int]
            ) -> bool:
        '''
        Return True if the question is correcte

        Args:
            overlap: int = The current overlap for the Recall@k
            student_chunk: tuple[int, int] = The student_chunk chunk start/end
            dataset_chunk: tuple[int, int] = The dataset_chunk chunk start/end
        Return:
            res: bool = The question 'state'
        '''
        # Calculate the true overlap start/end
        common_start: int = max([
            student_chunk[0], dataset_chunk[0]
        ])
        common_end: int = min([
            student_chunk[1], dataset_chunk[1]
        ])

        # Calculate the true overlap
        score: float = max([
            common_end - common_start, 0
        ]) / (dataset_chunk[1] - dataset_chunk[0]) * 100

        # Compare the true overlap with the minimum overlap
        return score >= overlap
